### ISSUE TITLE
TabItemTappedCommand on Hostview is set to private and not available

### ISSUE THREAD

**Issue by kplkasteel** [roubachof/Sharpnado.Tabs#41]
On The class TabHostView your Command: TabItemTappedCommand is set to private and therefore not available fo command excecution.

 line 229:  private ICommand TabItemTappedCommand { get; }
  
 Though it is possible to use the xamarin Community toolkit to convert the SelectedIndexChanged event to a command it would be much better if the command would become publicly available and thus make a command excecution possible when an item is selected.

**Comment by valentasm1** [comment]
Lets say you have two tabs. My tasks and All tasks. Basically you have same ui, just need load a bit different data. Doing async on properties it is nasty deal and having command would help a lot of.

**Comment by roubachof** [comment]
any PR is welcome :)

**Comment by roubachof** [comment]
Well you subscribe to the event and see if the value did change
Or you can bind to the SelectedIndex like this:

public int SelectedTabIndex
    {
        get => _selectedTab;
        set
        {
            if (SetProperty(ref _selectedTab, value))
            {
                OnSelectedTabChanged();
                RaisePropertyChanged(nameof(ShowEditActionFabButton));
                RaisePropertyChanged(nameof(ShowAddMediaFabButton));
            }
        }
    }

OnSelectedTab will only be called if the index did change

**Comment by vhugogarcia** [comment]
so, here is the issue I guess we are facing:

When binding the ViewSwitcher like this:
`<tabs:ViewSwitcher x:Name="Switcher"
   Animate="True"
   BindableLayout.ItemsSource="{Binding Items}"
   BindableLayout.ItemTemplateSelector="{StaticResource ItemsTemplateSelector}"
   SelectedIndex="{Binding SelectedItemIndex, Mode=TwoWay}" />`

I was able to retrieve the selected item on the changed event, just as @roubachof  mentioned it. 

My TabHostView also sets the ItemsSource Binding to the same {Binding Items}, however, the issue here is that, there is no way to dynamically pull the data when the tab is selected and update an individual view from the switcher. 🤔 

I even tried to update the ObservableCollection without luck.

so, I'm trying another workaround to make it work by using the OnSelectedTabChanged(); and even avoid any duplicated trigger. I will post my results.

**Comment by roubachof** [comment]
Guys please create an issue for every concrete problem. This is has nothing to do with the title of this issue.
I'm closing this issue.
