### ISSUE TITLE
Expose FontAttributes Field on TabTextItem

### ISSUE THREAD

**Issue by brentpbc** [roubachof/Sharpnado.Tabs#6]
First, thanks so much for your components they are super helpful!

**Is your feature request related to a problem? Please describe.**
I want to be able to bold the text on the UnderlinedTabItem, as per the TabStyle in the SillyApp! sample application FontSize and FontFamily are exposed but FontAttributes is not. I would like to keep using the default platform fonts but bold the tab item label for legibility/readability

**Describe the solution you'd like**
Expose FontAttributes field on TabTextItem

**Describe alternatives you've considered**
I tried researching the Xamarin font documentation https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/fonts and looked at the sample font app: https://github.com/xamarin/xamarin-forms-samples/tree/master/WorkingWithFonts but couldn't see how to create a font family without specifying a font file. I just want to use the standard platform fonts but with the bold attribute applied.

**Additional context**
See Image below, the thin lighter color font is hard to read for people with poor eyesight or in poor lighting conditions:
![image](https://user-images.githubusercontent.com/55366323/97664861-be1ba500-1ace-11eb-8b6d-f03332fa7cb2.png)

![Screen Shot 2020-10-30 at 4 50 22 pm](https://user-images.githubusercontent.com/55366323/97665808-7138ce00-1ad0-11eb-9304-197242881f4f.png)

I would be so grateful if you could slot this in or suggest a workaround :)

**Comment by roubachof** [comment]
the "bold" attribute is in fact a shorthand method to a bold font, so you just have to find which bold font you need :)

**Comment by tranb3r** [comment]
Sometimes you just want to use the default system font with Bold or Italic attributes.
The problem is that the default system font has no explicit family name, so to apply bold or italic you currently have to import a separate font—which kind of defeats the purpose of using the system font.

I think it would be very useful to have a FontAttributes property directly in the control.
@roubachof Would you consider reopening this issue? The implementation should be fairly straightforward.
